@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.techemistry.registration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;