@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.techemistry.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;