@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.techemistry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;